name: CI (lint + typecheck + format)
on:
  push:
    branches: [ main ]
  pull_request:
permissions:
  contents: read
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: TypeScript typecheck
        run: npm run typecheck

      - name: ESLint
        run: npm run lint

      - name: Prettier (check)
        run: npm run format
