# .github/workflows/format.yml
name: Format with Prettier
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - ".prettierrc"
      - "package.json"
jobs:
  format:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci --no-audit --no-fund
      - run: npx prettier --write .
      - name: Commit changes if any
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(format): apply Prettier"
            git push
          fi
