name: Refresh lockfile (Linux)
on:
  workflow_dispatch:
  push:
    paths:
      - "package.json"
jobs:
  lockfile:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      # Nettoyage pour forcer une résolution propre
      - run: rm -rf node_modules package-lock.json
      # Génère un package-lock.json compatible Linux sans installer dans node_modules
      - run: npm install --package-lock-only
      # Assure la cohérence en simulant une install CI
      - run: npm ci
      - name: Commit lockfile if changed
        run: |
          if [ -n "$(git status --porcelain package-lock.json)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add package-lock.json
            git commit -m "chore: refresh lockfile for Linux (SWC deps)"
            git push
          else
            echo "No changes to lockfile."
          fi
